Added comments to Sidebar and Container layouts
blackbaud-community/stache pull request #120
Opened 2017-01-10 21:36 UTC by blackbaud-brandonhare

Created a new partial for the comments. Did not update the blog pattern, as I didn't want to potentially break any existing stuff.

2017-01-11 22:05 UTC, Blackbaud-SteveBrush commented on src/partials/partial-disqus.hbs
> +    </div>
I think there's one too many closing `</div>` tags, here.

2017-01-11 22:06 UTC, blackbaud-brandonhare commented on src/partials/partial-disqus.hbs
> +    </div>
Two closing tags for two divs?

2017-01-11 22:06 UTC, blackbaud-brandonhare commented on src/partials/partial-disqus.hbs
> +    </div>
Ah crap, I see it.

2017-01-11 22:12 UTC, Blackbaud-SteveBrush commented on src/layouts/layout-container.hbs
> +        {{# inherit stache.config.comments comments }}
This is a boolean? If so, is it possible to use the boolean pattern from other boolean variables (ie, `showComments`)? If it's a pre-existing variable, don't worry about it.

2017-01-11 22:13 UTC, blackbaud-brandonhare commented on src/layouts/layout-container.hbs
> +        {{# inherit stache.config.comments comments }}
It's a preexisting variable. We use it in the blog pattern to enable comments there. It seemed silly to have two variables to enable comments in different places, so I just used that one.

2017-01-11 22:19 UTC, Blackbaud-SteveBrush commented on src/layouts/layout-container.hbs
> +        {{# inherit stache.config.comments comments }}
That's fine! I think this looks good.

2017-01-11 22:21 UTC, blackbaud-brandonhare commented
@Blackbaud-BobbyEarl?

2017-01-11 23:07 UTC, Blackbaud-BobbyEarl requested changes
layout-sidebar inherits from layout-container.  In this proposed state, turning on the comments would mean the divs + scripts would show up twice for layout-sidebar.

layout-blog also inherits from layout-sidebar, so turning on comments would have them show up three times.

It would mean the comments spanning the content + sidebar, but perhaps it's best in layout-base?  That would mean all layouts are supported, but visually it may not look as good.  We would have to remove them from the blog pattern in that scenario.

2017-01-12 14:41 UTC, blackbaud-brandonhare commented
@bobbyearl Yeah, I started out by adding it to base, but it looks terrible. I also didn't want to force people to turn off the comments in every container. I'd rather it be limited in scope. Is there a good way to restrict it to just the sidebar and container without the duplication?

2017-01-12 15:16 UTC, blackbaud-brandonhare commented
Yeah, I think this makes more sense to do as a one off for the specific project that needs it. I'm reluctant to commit to the code churn required to properly implement it lest we break a bunch of other things. Closing this.

2017-01-12 15:16 UTC, closed without merging